version: '3.8'

services:
  # Maven Build Service
  maven-build:
    image: maven:3.9.4-eclipse-temurin-17
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2 # Cache Maven dependencies
    command: mvn clean package
    networks:
      - app-network

  # Spring Boot Application
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - maven-build
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      RUN_TESTS: "false"

  # Cucumber Tests
  cucumber-tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - springboot-app
    environment:
      RUN_TESTS: "true" # Ensures tests are executed
    volumes:
      - ./results:/app/results # Save test results locally
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
